server:
  port: 8080

spring:
  application:
    name: coding-contest-backend
  
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
    
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
  
  h2:
    console:
      enabled: true

# Custom application properties
app:
  docker:
    image: "openjdk:17-slim"
    timeout-seconds: 30
    memory-limit: "128m"
  
  submission:
    queue-name: "submission-queue"
    max-retries: 3

# CORS Configuration
cors:
  allowed-origins: "http://localhost:5173,http://localhost:3000"
  allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
  allowed-headers: "*"

logging:
  level:
    ai.shodh: DEBUG
    org.springframework.web: INFO
