server:
  port: 8080

spring:
  application:
    name: coding-contest-backend
  
  datasource:
    url: jdbc:postgresql://ep-ancient-dust-adtlas52-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
    username: neondb_owner
    password: npg_X43TrnIyYElF
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  redis:
    host: ${SPRING_REDIS_HOST:redis}
    port: ${SPRING_REDIS_PORT:6379}
    timeout: 2000ms

# Custom application properties
app:
  docker:
    image: "openjdk:17-slim"
    timeout-seconds: 30
    memory-limit: "128m"
  
  submission:
    queue-name: "submission-queue"
    max-retries: 3

# CORS Configuration
cors:
  allowed-origins: "http://localhost:5173,http://localhost:3000"
  allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
  allowed-headers: "*"

logging:
  level:
    ai.shodh: INFO
    org.springframework.web: INFO
